<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[=====Browser Session Started=====]]>
    </line>
    <line>
      <![CDATA[=====Application Started=====]]>
    </line>
    <line>
      <![CDATA[=====Browser Session End=====]]>
    </line>
  </reporter-output>
  <suite started-at="2022-01-21T12:52:19 IST" name="Default suite" finished-at="2022-01-21T12:52:24 IST" duration-ms="5051">
    <groups>
    </groups>
    <test started-at="2022-01-21T12:52:19 IST" name="Default test" finished-at="2022-01-21T12:52:24 IST" duration-ms="5051">
      <class name="TestCases.ContactUsSuccessTest">
        <test-method is-config="true" signature="setupApplication()[pri:0, instance:TestCases.ContactUsSuccessTest@1a75e76a]" started-at="2022-01-21T12:52:19 IST" name="setupApplication" finished-at="2022-01-21T12:52:23 IST" duration-ms="4632" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====Browser Session Started=====]]>
            </line>
            <line>
              <![CDATA[=====Application Started=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupApplication -->
        <test-method is-config="true" signature="initiate()[pri:0, instance:TestCases.ContactUsSuccessTest@1a75e76a]" started-at="2022-01-21T12:52:23 IST" name="initiate" finished-at="2022-01-21T12:52:23 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiate -->
        <test-method is-config="true" signature="initiatehome()[pri:0, instance:TestCases.ContactUsSuccessTest@1a75e76a]" started-at="2022-01-21T12:52:23 IST" name="initiatehome" finished-at="2022-01-21T12:52:23 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiatehome -->
        <test-method signature="test1()[pri:0, instance:TestCases.ContactUsSuccessTest@1a75e76a]" started-at="2022-01-21T12:52:23 IST" name="test1" finished-at="2022-01-21T12:52:23 IST" duration-ms="68" status="FAIL">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[automationpractice.com]> but was:<[My Store]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[automationpractice.com]> but was:<[My Store]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at Pages.homepage.Pageverification(homepage.java:21)
at TestCases.ContactUsSuccessTest.test1(ContactUsSuccessTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:TestCases.ContactUsSuccessTest@1a75e76a]" started-at="2022-01-21T12:52:23 IST" name="closeApplication" finished-at="2022-01-21T12:52:24 IST" duration-ms="151" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[=====Browser Session End=====]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- TestCases.ContactUsSuccessTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
